name: Docker Build and Release
on: [ push ]
#env:
#### An dieser Stelle müssen eure persönlichen Umgebungsvariablen eingetragen werden
  # Tip: Die Token/der API-Key werden als Secrets in den Repository-Settings eingetragen und hier referenziert.
  # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        cache: maven
   
    #- name: Cache Maven packages
    #  uses: actions/cache@v1
    #  with:
    #    path: ~/.m2
    #    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    #    restore-keys: ${{ runner.os }}-m2
  
    - name: Compile, build and push
      run: |
        mvn package
        docker build --tag ghcr.io/Nikolai8/petclinic:latest -f Dockerfile .
        docker login --username nikolai8 --password ${{ secrets.REGISTRY_TOKEN }} ghcr.io
        docker push ghcr.io/Nikolai8/petclinic:latest
